on:
  push:
    branches:
      - rzadp/mdbook
      - rzadp/book

jobs:
  mdbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            # const prs = await github.paginate(github.rest.pulls.list, {...context.repo, state: 'open'})
            const prs = await github.paginate(github.rest.pulls.list, {owner: 'polkadot-fellows', repo: 'RFCs', state: 'open'})
            console.log(`Found ${prs.length} PRs.`)

            for (const pr of prs) {
              console.log(pr)
            }
